INSERT INTO dbo.Division (DivCode, Division) VALUES (1, 'Accessories');
INSERT INTO dbo.Division (DivCode, Division) VALUES (2, 'Bags');
INSERT INTO dbo.Division (DivCode, Division) VALUES (3, 'Beauty');
INSERT INTO dbo.Division (DivCode, Division) VALUES (4, 'BFL Services');
INSERT INTO dbo.Division (DivCode, Division) VALUES (5, 'Children');
INSERT INTO dbo.Division (DivCode, Division) VALUES (6, 'EJW');
INSERT INTO dbo.Division (DivCode, Division) VALUES (7, 'F&B');
INSERT INTO dbo.Division (DivCode, Division) VALUES (8, 'Home');
INSERT INTO dbo.Division (DivCode, Division) VALUES (9, 'LFL');
INSERT INTO dbo.Division (DivCode, Division) VALUES (10, 'Mens Underwear Sleepwear & Swimwear');
INSERT INTO dbo.Division (DivCode, Division) VALUES (11, 'Menswear');
INSERT INTO dbo.Division (DivCode, Division) VALUES (12, 'Shoes');
INSERT INTO dbo.Division (DivCode, Division) VALUES (13, 'Slippers & Slides');
INSERT INTO dbo.Division (DivCode, Division) VALUES (14, 'Socks');
INSERT INTO dbo.Division (DivCode, Division) VALUES (15, 'Sports Apparel');
INSERT INTO dbo.Division (DivCode, Division) VALUES (16, 'Sports Shoes');
INSERT INTO dbo.Division (DivCode, Division) VALUES (17, 'Tech');
INSERT INTO dbo.Division (DivCode, Division) VALUES (18, 'Toys');
INSERT INTO dbo.Division (DivCode, Division) VALUES (19, 'Travel');
INSERT INTO dbo.Division (DivCode, Division) VALUES (20, 'Wmn Lingerie Sleepwear & Swimwear');
INSERT INTO dbo.Division (DivCode, Division) VALUES (21, 'Womenswear');
